# Generated by Django 4.0.3 on 2022-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="product_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
